- setup.py
This PR adds the `~/opt` prefix to the paths where the `talib` can be found. It is useful to be able to install the C library on systems without admin (`sudo`) rights.
I don't care what the final prefix will be or if we want to make it somehow configurable (env variable?), so feel free to suggest other ways to add that path. :-)
> Provide at least one user writable path

- .gitignore
- docs/func_groups/cycle_indicators.md
- docs/func_groups/math_operators.md
- docs/func_groups/math_transform.md
- docs/func_groups/momentum_indicators.md
- docs/func_groups/overlap_studies.md
- docs/func_groups/pattern_recognition.md
- docs/func_groups/price_transform.md
- docs/func_groups/statistic_functions.md
- docs/func_groups/volatility_indicators.md
- docs/func_groups/volume_indicators.md
- docs/generate_html_pages.py
- requirements_dev.txt
- talib/__init__.py
Not a whole lot of changes here, despite the size of the diff. Mostly I did some cleanups to the markdown_to_html code:  
* I switched it to using the ``mistune`` library for the markdown conversion, in conjunction with ``pygments`` for code highlighting. 
* A bugfix for the OBV function's generated documentation (it wasn't correctly outputting that one function's parameters)
* The script now accepts an optional positional argument to specify a path for where to dump the generated html files (useful for dumping to a second directory checked out to the gh-pages branch)
> update documentation to warn about unstable functions

- talib/__init__.py
- talib/test_abstract.py
Fixes https://github.com/mrjbq7/ta-lib/issues/56, closes https://github.com/mrjbq7/ta-lib/pull/122
Another take at pd.Series support: a simple wrapper.
Allows for notebook code like:
~~Currently, only top-level `talib` namespace is patched.~~ Is this the preferred API (e.g. `import talib as ta; ta.SMA(...)`?
> Add pandas.Series support

- talib/_abstract.pxi
Attempting to run the following code:
```python
import talib.abstract as ta
import pandas as pd
import numpy as np
inputs = {
'open': np.random.random(100),
'high': np.random.random(100),
'low': np.random.random(100),
'close': np.random.random(100),
'volume': np.random.random(100)
}
dataframe = pd.DataFrame(inputs)
dataframe['minusdi'] = ta.MINUS_DI(dataframe)
dataframe['minusdi_25'] = ta.MINUS_DI(dataframe, timeperiod=25)
```
Raises the following exception:
```
~/dev/ta-lib/talib/_abstract.pxi in talib._ta_lib.Function.__call__()
381             self.set_input_arrays(input_arrays)
382             args = args[len(input_arrays):]
--> 383         elif len(input_arrays) or (not self.__input_arrays and (
384                 not len(args) or not isinstance(args[0], __INPUT_ARRAYS_TYPES))):
385 …
```
> fix subsequent calls to abstract TA functions using DataFrame as input arrays

- talib/_abstract.pxi
- talib/test_abstract.py
Another bugfix for https://github.com/mrjbq7/ta-lib/issues/306
Once again I didn't include `talib/_ta_lib.c`, generating it on Linux seems to strip out the Windows-specific stuffs :/
> do not cache input price series names in abstract Function.__call__

- Dockerfile
The changes in this commit reduce the Docker image size from >1 GB to 205 MB. Docker multi-stage builds were used to achieve this. In the first stage, the core ta-lib library is compiled, and the Python ta-lib package is installed. Then, in the second stage, the compiled core ta-lib library and the Python wheel files are copied over and installed. The second stage also uses the `python:VERSION-slim` Docker image, which is much smaller than the `python:VERSION` image, because it does not include any compilers or other software not necessary at runtime.
The build and run procedure is unchanged. Use `docker build --tag ta-lib .` to build and `docker run --rm -it ta-lib bash` to run.
Another change introduced by the commit is the option of skipping testing during image building. By default, …
> use multi-stage build to minimize size of Docker image

- .travis.yml
- requirements_dev.txt
- requirements_test.txt
Remove 2.7 and 3.5 due to end of life errors from Travis and updated the dist.
Also updated the other requirements to fix: "Building wheel for pandas (setup.py) ... error" in the travis 3.9 build.
> Additional fixes related to python 3.9

- README.md
There is a small typo in README.md.
Should read `underlying` rather than `underyling`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, underyling -> underlying

- tools/generate_func.py
- tools/generate_stream.py
If one build the C lib from sources (sourceforge trunk) and install it - the ta_func.h header in /usr/local/include/ will contain function declarations like:
```
TA_LIB_API TA_RetCode TA_ACOS( int    startIdx, ...
....
TA_LIB_API TA_RetCode TA_S_ACOS( int    startIdx, ...
...
TA_LIB_API int TA_ACOS_Lookback( void );
```
while `generate_*.py` scripts are likely expecting declarations without `TA_LIB_API` prefix like inside `http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz` and unable to parse the header from trunk. Which makes addition of a new indicator even more complicated.   
This simple patch should make scripts compatible with both headers.
> Support ta_func.h with TA_LIB_API declarations

- tools/threads_talib.py
Illustrates #540 but does *not* solve the problem.
Over at freqtrade, we are using ta-lib in a multithreaded fashion and we have noticed that, on occasion, the library will throw an error that looks like this:
```
File "/home/opc/freqtrade/user_data/strategies/EI3v2_RSI_CONS_TRAIL_AI.py", line 425, in populate_any_indicators
informative[f"%-{coin}rsi-period_{t}"] = ta.RSI(informative, timeperiod=t)
File "talib/_abstract.pxi", line 439, in talib._ta_lib.Function.__call__
File "talib/_abstract.pxi", line 350, in talib._ta_lib.Function.outputs
File "/home/opc/freqtrade/.env/lib64/python3.9/site-packages/pandas/core/series.py", line 442, in __init__
com.require_length_match(data, index)
File "/home/opc/freqtrade/.env/lib64/python3.9/site-packages/pandas/core/common.py", line 557, in …
```
> break threading for talib abstract with pandas

- talib/test_abstract.py
Pandas 1.5.0 is now raising an exception when the columns argument is a set. As such, the test should be adjusted to also work with the latest pandas version.
> [DataFrame](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.html#pandas.DataFrame) constructor raises if index or columns arguments are sets ([GH47215](https://github.com/pandas-dev/pandas/issues/47215))
source: [pandas releaselog](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.5.0.html#other-api-changes)
side note: Ci would currently be failing without this fix - since 1.5.0 is out (which happened on sept 19th).
> Fix pytest error with pandas 1.5.0

- README.md
numpy.array and np.nan was used in same line, which is a bit confusing.
> Unify numpy import in readme

- tools/install-macos.sh
Check if OS is of Apple Silicon architecture to prep pip install with the correct path.
> Set path for Apple Silicon architectures

- .github/workflows/tests.yml
Bump pre-built actions to their latest major version
While it's not necessarily a problem to use older actions - it's better to use the latest version.
(on top of that, `setup-python@v4` now has a `allow-prereleases: true` flag - which will allow testing against 3.12 (which currently fails as `distutils` no longer exists - but is a topic for another time).
> Bump pre-built actions to their latest major version

- pyproject.toml
With the release of numpy2.0, ta-lib is no longer installable (the build fails), as it's currently incompatible with numpy 2.x.
While that should be addressed too - I'm not sure it's a "quick fix" that can be done with just a few lines of code (or while keeping compatibility with older numpy versions).
i therefore think it's better to have a "quick fix" available so it's at least not breaking existing setups / installations.
Regular version-pinning is not relevant here - as it's the numpy version during build-time (a separate, isolated environment created while building a package) that's the problem currently.
Temporarily solves #655
Alternative workarounds: Disable build isolation.
```
pip install "numpy<2"
pip install TA-Lib -v --no-build-isolation
```
---
To test this:
install ta-lib …
> Add build-requires pinning numpy to <2

- talib/__init__.py
- talib/_abstract.pxi
Broadly speaking, there are two categories of `ImportError`: the module does not exist, or the module exists but failed to be imported. Currently, both are silently ignored; however, the latter category of error should be propagated up the stack so that the developer can investigate and resolve the issue.
> Propagate Pandas/Polars import errors when the module exists but failed to be imported

- .github/workflows/build.yml
- tools/build_wheel_linux.sh
- tools/build_wheel_macos.sh
- tools/build_wheel_windows.cmd
I am trying to build wheels TA-Lib across multiple platforms and architectures with  GitHub Actions workflow. The workflow is triggered when a new tag starting with v* is pushed.
The workflow builds wheels for:
* Linux: ManyLinux (x86_64) and MuslLinux (x86_64)
* Windows: AMD64 and x86
* macOS: x86_64 and arm64
PR Details:
* add `build_wheel_windows.cmd`, `build_wheel_linux.sh` and `build_wheel_linux.sh` under the tools folder
* add `build.yml` under the workflow using pypa/cibuildwheel to handle the wheel-building process.
Currently, the workflow uploads the built wheels as GitHub artifacts. The PyPI Uploading or Github Release Uploading steps are not yet implemented.
Additionally, since the project already has a test workflow, I skipped all tests to speed up the build process (running …
> Add GitHub Actions workflow for automated Python wheel builds across multiple platforms

- README.md
changed emojis from shortcodes to real ones, i hope it renders now well on pypi
> changed emojis from shortcodes to real ones

- MANIFEST.in
The `_ta_lib.pxd` and `common.pxd` files are missing in the source distribution, `ta_lib-0.6.6.tar.gz`, on PyPI and GitHub, such that building from source fails.
```
running build_ext
Error compiling Cython file:
------------------------------------------------------------
...
cimport _ta_lib as lib
^
------------------------------------------------------------
talib\_common.pxi:1:8: '_ta_lib.pxd' not found
```
> Fix .pxd files missing is source distribution

- pyproject.toml
packages shouldn't usually depend on pip unless they actually need it (import from it etc).
currently - when installing ta-lib in an uv venv (which usually doensn't come with pip) - pip is installed as dependency of ta-lib.
to reproduce:
```
uv venv
. .venv/bin/activate
uv pip install ta-lib
uv pip show pip
```
which outputs:
```
Name: pip
Version: 25.2
Location: /home/xmatt/devel/.venv/lib/python3.13/site-packages
Requires:
Required-by: ta-lib    <-- pip is only installed due to ta-lib
```
if dependencies of pip were required (there ain't any) - then these should be listed instead.
> chore: don't depend on pip
